---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: dvl1987
data:
  TIME_FREQ: "10"
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - image: busybox
    name: time-check
    resources: {}
    env:
    - name: config
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    command: [ 'while true: do date; sleep $TIME_FREQ;done' ]
    volumeMounts:
    - mountPath: /op/time
      name: time-check
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: time-check
    emptyDir: {}
status: {}