apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-busybox
  name: my-busybox
  namespace: dev2406
spec:
  containers:
  - image: busybox
    name: secret
    resources: {}
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /etc/secret-volume
      name: secret-volume
      readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "q3"
    operator: "Equal"
    value: "t"
    effect: "NoSchedule"
status: {}