apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs
    - name: sidecar-container
      image: ubuntu:latest
      command:
        - ["/bin/bash", "-c", "while true, do cat /var/log/nginx.log/var/log/error.log;sleep 30;done"]
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs
  volumes:
    - name: shared-logs
      emptyDir: {}
