apiVersion: v1
kind: Service
metadata: 
  name: node-service-nautilus
  namespace: node-namespace-nautilus
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
  selector:
   name: node-app
