---
apiVersion: v1
kind: Service
metadata: 
  name: redis-master
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-pod-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis-pod-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod-master
  template:
    metadata:
      labels:
        app: redis-pod-master
    spec:
      containers:
      - name: master-redis-devops
        image: redis
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 6379
