apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deploy
  namespace: nautilus
  labels:
    app: httpd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: httpd-pod
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.27
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: httpd-service
  namespace: nautilus
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
   name: httpd
