---
apiVersion: v1
kind: Service
metadata: 
  name: redis-slave
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-pod-slave

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis-pod-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-pod-slave
  template:
    metadata:
      labels:
        app: redis-pod-slave
    spec:
      containers:
      - name: slave-redis-nautilus
        image: gcr.io/google_samples/gb-redisslave:v3
        env:
        - name: GET_HOSTS_FROM
          value: dns
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 6379
