apiVersion: v1
kind: Pod
metadata:
  name: secret-nautilus
spec:
  containers:
    - name: secret-container-nautilus
      image: debian:latest
      command:
        [ '/bin/bash','-c','sleep 10000' ]
      volumeMounts:
        - mountPath: /opt/apps
          name: secret-volume-devops 
  volumes:
    - name: secret-volume-devops
      secret:
        secretName: beta
