apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  generation: 1
  name: default-deny
  namespace: default
  resourceVersion: "4449"
spec:
  podSelector:
    matchLabels:
      run: secure-pod
  policyTypes:
  - Ingress
  ingress:
  - from:
     - podSelector:
        matchLabels:
          run: secure-pod
    ports:
    - protocol: TCP
      port: 80