apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: nginx
    name: jupiter
    resources: {}
    env: 
    - name: type
      value: planet
  - image: busybox
    name: europa
    command: 
    - sleep
    - "4800"
    env:
    - name: type
      value: moon
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}