---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: dvl1987
data:
  TIME_FREQ=10
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
spec:
  containers:
  - image: busybox
    name: time-check
    resources: {}
    command: [ 'while true: do date; sleep $TIME_FREQ;done' ]
    volumeMounts:
    - mountPath: /op/time/time-check.log
      name: time-check
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: time-check
    hostPath:
      path: /opt/time
      type: DirectoryOrCreate
status: {}