apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        volumeMounts:
        - name: data
          mountPath: 
        - name: redis
          mountPath: 
        resources:
          requests:
            cpu: "0.2"
        volumes:
        - name: data
          emptyDir: {}
        - name: 
status: {}